services:
  postgres:
    image: postgres:16-alpine
    container_name: commerce_core_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: commerce_core_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: commerce_core_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_1
      - api_2

  api_1:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://root:rootpassword@postgres:5432/commerce_core_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  api_2:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://root:rootpassword@postgres:5432/commerce_core_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: