name: Commerce Core CI/CD

on:
  push:
    branches: ["Main", "master"]
  pull_request:
    branches: ["Main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"

      REDIS_HOST: "localhost"
      REDIS_PORT: 6379

      STRIPE_SECRET_KEY: "dummy_stripe_key"
      STRIPE_WEBHOOK_SECRET: "dummy_stripe_secret"

      JWT_ACCESS_SECRET: "dummy_access_secret"
      JWT_REFRESH_SECRET: "dummy_refresh_secret"
      JWT_ACCESS_EXPIRES_IN: "dummy_access_expires"
      JWT_REFRESH_EXPIRES_IN: "15m"

      GOOGLE_CLIENT_ID: "dummy_google_id"
      GOOGLE_CLIENT_SECRET: "dummy_google_secret"
      GOOGLE_CALLBACK_URL: "http://dummy/google/callback"

      CLOUDINARY_CLOUD_NAME: "dummy_cloudinary_name"
      CLOUDINARY_API_KEY: "dummy_cloudinary_key"
      CLOUDINARY_API_SECRET: "dummy_cloudinary_secret"

      FACEBOOK_APP_ID: "dummy_facebook_id"
      FACEBOOK_APP_SECRET: "dummy_facebook_secret"
      FACEBOOK_CALLBACK_URL: "http://dummy/facebook/callback"

      TWITTER_CONSUMER_KEY: "dummy_twitter_key"
      TWITTER_CONSUMER_SECRET:  "dummy_twitter_secret"
      TWITTER_CALLBACK_URL:  "http://dummy/twitter/callback"
      
      MAIL_HOST: "smtp.gmail.com"
      MAIL_PORT: 587
      MAIL_USER:  "indat0011@gmail.com"
      MAIL_PASS:  "dummy_pass"
      MAIL_FROM: "'E-Commerce System' <noreply@ecommerce.com>"

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: dummy
          POSTGRES_PASSWORD: dummy
          POSTGRES_DB: dummy
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U dummy -d dummy"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Kéo source code
        uses: actions/checkout@v4

      - name: Cài đặt Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Cài đặt dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build
        run: npm run build

      - name: Unit Test
        run: npm run test

      - name: E2E Test
        run: npm run test:e2e